export default {
	install(Vue, options) {
		Vue.prototype.$abbreviations = [
			{ k: 'AE', v: 'L\'Année épigraphique' },
			{ k: 'AIJ', v: 'Antike Inschriften aus Jugoslavien. Heft 1. Noricum und Pannonia superior.  Bearbeitet von Viktor Hoffiller und Balduin Saria' },
			{ k: 'BAC', v: 'Bulletin archéologique du Comité des Travaux Historiques et Scientifiques' },
			{ k: 'BCAR', v: 'Bullettino della Commissione Archeologica Comunale di Roma' },
			{ k: 'Besevliev', v: 'Beševliev, Spätgriechische und spätlateinische Inschriften aus Bulgarien' },
			{ k: 'Bloch', v: 'Bloch, Supplement to volume XV, 1 of the Corpus Inscriptionum Latinarum including complete indices to the Roman brick-stamps (1948) [= The Roman brick-stamps not published in volume XV 1 of the „Corpus Inscriptionum Latinarum“, HSCP 56–57, 1947, 1–128 + Indices to the Roman brick-stamps published in volume XV 1 of the Corpus Inscriptionum Latinarum and LVI–LVII of the Harvard Studies in Classical Philology, HSCP 58–59, 1948, 1–104]' },
			{ k: 'Bruns', v: 'Fontes iuris Romani antiqui. Edidit Carolus Georgius Bruns. Post curas Theodori Mommseni editionibus quintae et sextae adhibitas septimum edidit Otto Gradenwitz. Pars prior. Leges et negotia (1909)' },
			{ k: 'CBFIR', v: 'Der römische Weihebezirk von Osterburken I. Schallmayer; Eibl; Ott; Preuss; Wittkopf, Corpus der griechischen und lateinischen Beneficiarier-Inschriften des Römischen Reiches' },
			{ k: 'Ceska/Hosek', v: 'Češka; Hošek, Inscriptiones Pannoniae superioris in Slovacia Transdanubiana asservatae' },
			{ k: 'Cholodniak', v: 'Cholodniak, Carmina sepulcralia Latina epigraphica' },
			{ k: 'CIB', v: 'Veny, Corpus de las inscripciones balearicas hasta la domincion arabe' },
			{ k: 'CIE', v: 'Corpus Inscriptionum Etruscarum' },
			{ k: 'CIG', v: 'Corpus Inscriptionum Graecarum' },
			{ k: 'CIGP', v: 'Kovács, Corpus Inscriptionum Graecarum Pannonicarum' },
			{ k: 'CII', v: 'Corpus Inscriptionum Iudaicarum. Recueil des inscriptions juives qui vont du IIIe siècle avant Jésus-Christ au VIIe siècle de notre ère. Vol. I. Europe. Par Jean-Baptiste Frey (1936) [= Corpus of Jewish inscriptions. Jewish inscriptions from the third century B.C. to the seventh century A.D. Volume I. Europe (1975)]' },
			{ k: 'CIIP', v: 'Corpus inscriptionum Iudaeae/Palestinae. A multi-lingual corpus of the inscriptions from Alexander to Muhammad' },
			{ k: 'CILA', v: 'CILA 1 = Corpus de Inscripciones latinas de Andalucía 1. Huelva (1989). CILA 2 = Corpus de Inscripciones latinas de Andalucía 2. Sevilla [1 (1991): n. 1–338. 2 (1991): n. 339–610; 1*–26*. 3 (1996): n. 611–1011. 4 (1996): n. 1012–1255; 27*–52*]. CILA 3 = Corpus de Inscripciones latinas de Andalucía 3. Jaén [1 (1991): n. 1–355,. 2 (1991): n. 356–645]. CILA 4 = Corpus de Inscripciones latinas de Andalucía 4. Granada (2002)' },
			{ k: 'CIMRM', v: 'Vermaseren, Corpus inscriptionum et monumentorum religionis Mithriacae' },
			{ k: 'CLE', v: 'Buecheler, Carmina Latina epigraphica' },
			{ k: 'Corinth VIII 2', v: 'Corinth. Results of Excavations conducted by the American School of Classical Studies at Athens. Volume VIII, Part II. Latin inscriptions 1896–1926 edited by Allen Brown West' },
			{ k: 'Corinth VIII 3', v: 'Corinth. Results of Excavations conducted by the American School of Classical Studies at Athens. Volume VIII, Part III. The inscriptions 1926–1960 edited by John Harvey Kent' },
			{ k: 'Dobo', v: 'Inscriptiones extra fines Pannoniae Daciaeque repertae ad res earundem provinciarum pertinentes quas collegit adnotationibusque instruxit Arpadus Dobó. Editio quarta aucta et emendata' },
			{ k: 'Dougga', v: 'Dougga, fragments d’histoire. Choix d’inscriptions latines éditées, traduites et commentées (Ier – IVe siècles). Sous la direction de Mustapha Khanoussi et Louis Maurin' },
			{ k: 'EE', v: 'Ephemeris epigraphica' },
			{ k: 'Engström', v: 'Carmina Latina Epigraphica post editam collectionem Buechelerianam in lucem prolata conlegit Einar Engström' },
			{ k: 'ERCanosa', v: 'Le epigrafi romane di Canosa. A cura di Marcella Chelotti, Rosanna Gaeta, Vincenza Morizio, Marina Silvestrini. Coordinatori Francesco Grelle, Mario Pani' },
			{ k: 'Fiebiger - Schmidt', v: 'Fiebiger; Schmidt, Inschriftensammlung zur Geschichte der Ostgermanen' },
			{ k: 'Fiebiger - Schmidt II', v: 'Fiebiger; Schmidt, Inschriftensammlung zur Geschichte der Ostgermanen. Neue Folge' },
			{ k: 'Fiebiger - Schmidt III', v: 'Fiebiger; Schmidt, Inschriftensammlung zur Geschichte der Ostgermanen. Zweite Folge' },
			{ k: 'FIRA', v: 'Fontes iuris Romani Anteiustininiani' },
			{ k: 'French, Rom. Roads and Milestones of Asia Minor', v: 'French, Roman Roads and Milestones of Asia Minor. Fasc. 2. An interim catalogue of Milestones' },
			{ k: 'Gerstl, Suppl. CIL III', v: 'Gerstl, Supplementum epigraphicum zu CIL III für Kärnten und Osttirol 1902–1961' },
			{ k: 'GLISwedish', v: 'Thomasson, A Survey of Greek and Latin Inscriptions on Stone in Swedish Collections' },
			{ k: 'Graffiti del Palatino', v: 'Graffiti del Palatino. I. Paedagogium a cura di Heikki Solin e Marja Itkonen-Kaila (1966). II. Domus Tiberiana a cura di Paavo Castrén e Henrik Lilius (1970)' },
			{ k: 'HAE', v: 'Hispania Antiqua Epigraphica' },
			{ k: 'HEp.', v: 'Hispania Epigraphica' },
			{ k: 'Hild, Suppl. CIL III', v: 'Hild, Supplementum epigraphicum zu CIL III. Das pannonische Niederösterreich, Burgenland und Wien 1902–1968' },
			{ k: 'Howald/Meyer', v: 'Howald; Meyer, Die römische Schweiz' },
			{ k: 'I. v. Perge', v: 'Inschriften griechischer Städte aus Kleinasien. Bd. 54. Die Inschriften von Perge. T. I. (Vorrömische Zeit, frühe und hohe Kaiserzeit). Herausgegeben von Sencer Şahin' },
			{ k: 'IAM II', v: 'Inscriptions antiques du Maroc. II. Inscriptions latines (1982)' },
			{ k: 'IAM II Suppl.', v: 'Inscriptions antiques du Maroc. II. Inscriptions latines (1982). Supplément (2003)' },
			{ k: 'IAmpur.', v: 'Almagro, Las inscripciones ampuritanas griegas, ibéricas y latinas' },
			{ k: 'IBC', v: 'Hübner, Inscriptiones Britanniae Christianae' },
			{ k: 'ICERV', v: 'Vives, Inscripciones cristianas de la España romana y visigoda' },
			{ k: 'ICG', v: 'Le Blant, Inscriptions chrétiennes de la Gaule antérieures au VIIIe siècle. Tome I. Provinces Gallicanes (1856). Tome II. Les Sept provinces (1865)' },
			{ k: 'ICI', v: 'Inscriptiones Christianae Italiae septimo saeculo antiquiores' },
			{ k: 'ICret', v: 'Guarducci, Inscriptiones Creticae: I. Tituli Cretae mediae praeter Gortynios (1935). II. Tituli Cretae occidentalis (1939). III. Tituli Cretae orientalis (1942). Tituli Gortynii (1950)' },
			{ k: 'ICVR', v: 'de Rossi, Inscriptiones christianae urbis Romae septimo saeculo antiquiores' },
			{ k: 'ICVR n. s.', v: 'Silvagni; Ferrua, Inscriptiones christianae urbis Romae septimo saeculo antiquiores' },
			{ k: 'IDR', v: 'Inscriptiile Daciei Romane. I. Prolegomena historica et epigraphica diplomata militaria, tabulae ceratae. II. Pars meridionalis, inter Danuvium et Carpatos montes. III. Dacia Superior. 1. Pars occidentalis (ager inter Danuvium, Pathisium Marisiamquae). 2. Ulpia Traiana Dacica (Sarmizegetusa). 3. Pars media (ager inter Ulpiam Traianam, Miciam, Apulum, Alburnum Maiorem et flumen Crisium). 4. Pars orientalis. 5. Apulum. 6. Apulum – Instrumentum domesticum' },
			{ k: 'IG', v: 'Inscriptiones Graecae' },
			{ k: 'IGB', v: 'Michajlov, Inscriptiones Graecae in Bulgaria repertae. Volumen I. Inscriptiones orae Ponti Euxini. Editio altera emendata' },
			{ k: 'IGLS', v: 'Inscriptions grecques et latines de la Syrie. I. Commagène et Cyrrhestique (1929) [n. 1–256]. II. Chalcidique et Antiochène (1939) [n. 257–698]. III, 1. Région de l’Amanus. Antioche (1950) [. 699–988]. III, 2. Antioche (Suite). Antiochene (1953) [n. 989–1242]. IV. Laodicée. Apamène (1955) [n. 1243–1997]. V. Émésène (1959) [n. 1998–2710]. VI. Baalbek et Beqa‘ (1967) [n. 2711–3017]. VII. Arados et régions voisines (1970) [n. 4001–4061]. VIII, 3. Les inscriptions forestières d’Hadrien dans le Mont Liban (1980). XIII, 1. Bostra (1982) [n. 9001–9472]. XXI. Inscriptions de la Jordanie II. Région centrale (1986). XXI. Inscriptions de la Jordanie IV. Pétra et la Nabatène méridionale (1993). XXI. Inscriptions de la Jordanie V. La Jordanie du Nord-Est 1 (2009)' },
			{ k: 'IGRR', v: 'Cagnat, Inscriptiones Graecae ad res Romanas pertinentes' },
			{ k: 'IGUR', v: 'Moretti, Inscriptiones Graecae urbis Romae' },
			{ k: 'IHC', v: 'Hübner, Inscriptiones Hispaniae Christianae' },
			{ k: 'IJO', v: 'Inscriptiones Judaicae Orientis. Volume I. Eastern Europe. Band II. Kleinasien. Volume III. Syria and Cyprus' },
			{ k: 'IK', v: 'Inschriften griechischer Städte aus Kleinasien' },
			{ k: 'IKöln2', v: 'Galsterer, B.; Galsterer, H., Die römischen Steininschriften aus Köln. IKöln²' },
			{ k: 'ILA Arvernes', v: 'Inscriptions Latines d’Aquitaine (I.L.A.). Rémy, Arvernes' },
			{ k: 'ILA Bordeaux', v: 'Inscriptions Latines d’Aquitaine (I.L.A.). Maurin; Navarro Caballero, Bordeaux' },
			{ k: 'ILA Lectoure', v: 'Inscriptions Latines d’Aquitaine (I.L.A.). Fabre; Sillières, Lectoure' },
			{ k: 'ILA Nitiobroges', v: 'Inscriptions Latines d’Aquitaine (I.L.A.). Fages; Maurin, Nitiobroges' },
			{ k: 'ILA Pétrucores', v: 'Inscriptions Latines d’Aquitaine (I.L.A.). Bost; Fabre, Pétrucores' },
			{ k: 'ILA Santons', v: 'Inscriptions Latines d’Aquitaine (I.L.A.). Thauré; Tassaux, Santons' },
			{ k: 'ILA Vellaves', v: 'Inscriptions Latines d’Aquitaine (I.L.A.). Rémy, Vellaves' },
			{ k: 'ILAfr.', v: 'Cagnat; Merlin; Chatleain, Inscriptions latines d’Afrique (Tripolitaine, Tunisie, Maroc)' },
			{ k: 'ILAlg.', v: 'Gsell, Inscriptions latines de l’Algérie' },
			{ k: 'ILAlpes', v: 'Inscriptions Latines des Alpes  (I.L.Alpes). I. Rémy, Alpes Graies' },
			{ k: 'ILB', v: 'Gerov, Inscriptiones Latinae in Bulgaria repertae (Inscriptiones inter Oescum et Iatrum repertae) curante  Mihailov' },
			{ k: 'ILCV', v: 'Diehl, Inscriptiones Latinae Christianae veteres' },
			{ k: 'ILER', v: 'Vives, Inscripciones latinas de la España romana' },
			{ k: 'ILGN', v: 'Espérandieu, Inscriptions latines de Gaule (Narbonnaise)' },
			{ k: 'ILGR', v: 'Šašel Kos, Inscriptiones Latinae in Graecia repertae. Additamenta ad CIL III' },
			{ k: 'ILJug.', v: 'ILJug. I = Inscriptiones Latinae quae in Iugoslavia inter annos MCMXL et MCMLX repertae et editae sunt  (1963) [n. 1–451]. ILJug. II = Inscriptiones Latinae quae in Iugoslavia inter annos MCMLX et MCMLXX repertae et editae sunt  (1978) [n. 452–1222]. ILJug. III = Inscriptiones Latinae quae in Iugoslavia inter annos MCMII et MCMXL repertae et editae sunt  (1986) [n. 1223–3128]' },
			{ k: 'ILLPRON', v: 'Inscriptionum lapidariarum latinarum provinciae Norici usque ad annum MCMLXXXIV repertarum indices. Fasciculus primus. Catalogus' },
			{ k: 'ILLRP', v: 'Degrassi, Inscriptiones Latinae liberae rei publicae' },
			{ k: 'ILM', v: 'Chatelain, Inscriptions latines du Maroc' },
			{ k: 'ILN I Frèjus', v: 'Inscriptions latines de Narbonnaise (I.L.N.). [I.] Gascou; Janon, Fréjus' },
			{ k: 'ILN II Antibes', v: 'Inscriptions latines de Narbonnaise (I.L.N.). II. Chastagnol, Antibes, Riez, Digne' },
			{ k: 'ILN II Digne', v: 'Inscriptions latines de Narbonnaise (I.L.N.). II. Chastagnol, Antibes, Riez, Digne' },
			{ k: 'ILN II Riez', v: 'Inscriptions latines de Narbonnaise (I.L.N.). II. Chastagnol, Antibes, Riez, Digne' },
			{ k: 'ILN III Aix-en-Provence', v: 'Inscriptions latines de Narbonnaise (I.L.N.). III. Gascou, Aix-en-Provence' },
			{ k: 'ILN IV Apt', v: 'Inscriptions latines de Narbonnaise (I.L.N.). IV. Gascou; Leveau; Rimbert, Apt.' },
			{ k: 'ILN VI Alba', v: 'Inscriptions latines de Narbonnaise (I.L.N.). VI.' },
			{ k: 'ILN V. 1 Vienne', v: 'Inscriptions latines de Narbonnaise (I.L.N.). V. Vienne. Sous la direction de Bernard Rémy. 1 2003' },
			{ k: 'ILN V. 2 Vienne', v: 'Inscriptions latines de Narbonnaise (I.L.N.). V. Vienne. Sous la direction de Bernard Rémy. 2 2004' },
			{ k: 'ILN V. 3 Vienne', v: 'Inscriptions latines de Narbonnaise (I.L.N.). V. Vienne. Sous la direction de Bernard Rémy. 3 2005' },
			{ k: 'ILN VII. 1 Die', v: 'Inscriptions latines de Narbonnaise (I.L.N.). VII. Rémy; Desaye, Les Voconces. 1. Die 2012' },
			{ k: 'ILP', v: 'Mello; Voza, Le iscrizioni latine di Paestum' },
			{ k: 'ILPG', v: 'Pastor Muñoz; Mendoza Eguaras, Inscripciones latinas de la provincia de Granada' },
			{ k: 'ILS', v: 'Dessau, Inscriptiones Latinae selectae' },
			{ k: 'ILSard.', v: 'Sotgiu, Iscrizioni latine della Sardegna (Supplemento al Corpus Inscriptionum Latinarum, X e all’Ephemeris Epigraphica, VIII.)' },
			{ k: 'ILSl', v: 'Inscriptiones Latinae Sloveniae' },
			{ k: 'ILT', v: 'Merlin, Inscriptions latines de la Tunisie' },
			{ k: 'ILTG', v: 'Wuilleumier, Inscriptions latines des trois Gaules (France)' },
			{ k: 'IMS', v: 'Inscriptions de la Mésie Supérieure. I. Singidunum et le Nord-Ouest de la province. II. Viminacium et Margum. III. 2. Timacum Minus et la vallée du Timok. IV. Naissus – Remesiana – Horreum Margi. VI. Scupi et la Région de Kumanovo' },
			{ k: 'Inscr. Aq.', v: 'Brusin, Inscriptiones Aquileiae' },
			{ k: 'Inscr. It.', v: 'Inscriptiones Italiae' },
			{ k: 'Inscr. Saloni.', v: 'Bulić, Inscriptiones quae in C. R. Museo archaeologico Salonitano Spalati asservantur' },
			{ k: 'IOSPE', v: 'Latysev, Inscriptiones antiquae orae septentrionalis Ponti Euxini Graecae et Latinae' },
			{ k: 'IRAlm.', v: 'Lázaro Pérez, Inscripciones romanas de Almeria' },
			{ k: 'IRC', v: 'Inscriptions romaines de Catalogne. I. Barcelone (sauf Barcino). II. Lérida. III. Gérone. IV. Barcino' },
			{ k: 'IRCP', v: 'd\'Encarnaçao, Inscriçoes romanas do conventus Pacensis' },
			{ k: 'IRN', v: 'Mommsen, Inscriptiones regni Neapolitani latinae' },
			{ k: 'IRT', v: 'Reynolds; Ward Perkins, The Inscriptions of Roman Tripolitania' },
			{ k: 'ISard.', v: 'Sardis. Publications of the American Society for the excavation of Sardis. Volume VII. Greek and Latin inscriptions' },
			{ k: 'ISM', v: 'Inscriptiile din Scythia Minor grecesti si latine' },
			{ k: 'IvE', v: 'Die Inschriften von Ephesos' },
			{ k: 'IvM', v: 'Inschriften von Milet' },
			{ k: 'IvPergamon', v: 'Fränkel, Die Inschriften von Pergamon' },
			{ k: 'JIWE', v: 'Noy, Jewish inscriptions of Western Europe. Volume I. Italy (excluding the City of Rome), Spain and Gaul. Volume II. The City of Rome' },
			{ k: 'Kränzel - Weber (1997)', v: 'Kränzel; Weber, Die römerzeitlichen Inschriften aus Rom und Italien in Österreich' },
			{ k: 'Lehner', v: 'Lehner, Die antiken Steindenkmäler des Provinzialmuseums in Bonn' },
			{ k: 'LIA', v: 'Corpus des inscriptions latines d’Albanie' },
			{ k: 'MAMA', v: 'Monumenta Asiae Minoris antiqua' },
			{ k: 'Miliarios Tarraconense', v: 'Lostal Pros, Los miliarios de la provincia tarraconense (Conventos tarraconense, cesaraugustano, cluniense y cartaginense)' },
			{ k: 'Mourir à Dougga', v: 'Mourir à Dougga. Recueil des inscriptions funéraires. Sous la direction de Mustapha Khanoussi et Louis Maurin' },
			{ k: 'Novae', v: 'Inscriptions latines de Novae. Par Violeta Božilova, Jerzy Kolendo et Leszek Mrozewicz. Sous la rédaction de Jerzy Kolendo' },
			{ k: 'NRICG', v: 'Le Blant, Nouveau recueil des inscriptions chrétiennes de la Gaule antérieures au VIIIe siècle' },
			{ k: 'NS', v: 'Atti della Accademia Nazionale dei Lincei. Notizie degli scavi di antichità' },
			{ k: 'OGIS', v: 'Dittenberger, Orientis Graeci inscriptiones selectae' },
			{ k: 'Oxé/Comfort', v: 'Oxé; Comfort, Corpus vasorum Arretinorum' },
			{ k: 'Pais', v: 'Corporis inscriptionum Latinarum supplementa Italica. Fasciculus I. Pais, Addidamenta ad vol. V Galliae Cisalpinae' },
			{ k: 'Pikhaus', v: 'Pikhaus, Répertoire des inscriptions Latines versifiées de l\'Afrique Romaine (Ier – VIe siècles). I. Tripolitaine, Byzacène, Afrique proconsulaire.' },
			{ k: 'Popescu', v: 'Popescu, Inscriptiile grecesti si latine din secolele IV–XIII descoperite în România' },
			{ k: 'RIB', v: 'Collingwood; Wright, The Roman inscriptions of Britain' },
			{ k: 'RICG', v: 'Recueil des inscriptions chrétiennes de la Gaule antérieures à la Renaissance carolingienne' },
			{ k: 'RIT', v: 'Alföldy, Die römischen Inschriften von Tarraco' },
			{ k: 'RIU', v: 'Die römischen Inschriften Ungarns. 1. Lieferung (1972): Savaria, Scarbantia und die Limes-Strecke Ad Flexum – Arrabona [n. 1–284]. 2. Lieferung (1976): Salla, Mogentiana, Mursella, Brigetio [n. 285–634]. 3. Lieferung (1981): Brigetio (Fort.) und die Limesstrecke am Donauknie [n. 635–948]. 4. Lieferung (1984): Das Gebiet zw. der Drau u. der Limesstrecke Lussonium – Altinum [n. 949–1050]. 5. Lieferung (1991): Intercisa [n. 1051–1297]. 6. Lieferung (2001): Das Territorium von Aquincum ... [n. 1298–1561b]' },
			{ k: 'RIU Suppl.', v: 'Kovács, Tituli Romani in Hungaria reperti. Supplementum (2005)' },
			{ k: 'RMD', v: 'RMD I = Margaret M. Roxan, Roman military diplomas 1954–1977 (1978) [n. 1–78]. RMD II = Margaret M. Roxan, Roman military diplomas 1978 to 1984 (1985) [n. 79–135]. RMD III = Margaret M. Roxan, Roman military diplomas 1985–1993 (1994) [n. 136–201]. RMD IV = Margaret Roxan; Paul Holder, Roman military diplomas IV (2003) [n. 202–322]. RMD V = Paul Holder, Roman military diplomas V (2006) [n. 323–476]' },
			{ k: 'Rugo', v: 'Rugo, Le iscrizioni dei sec. VI – VII – VIII esistenti in Italia' },
			{ k: 'Samothrace', v: 'Samothrace. Vol. 2, 1: Fraser, The inscriptions on stone' },
			{ k: 'Sched. XVIII/1', v: 'Scheden zum Carmina-Band Stadt Rom' },
			{ k: 'SEG', v: 'Supplementum epigraphicum Graecum' },
			{ k: 'Segre', v: 'Segre, Iscrizioni di Cos [red. di Dina Peppas Delmousou ... et al.]' },
			{ k: 'Spomenik', v: 'Spomenik' },
			{ k: 'Suppl. It.', v: 'Supplementa Italica. Nuova serie' },
			{ k: 'Suppl. It. – Latium vetus', v: 'Supplementa Italica — Imagines: Supplementi fotografici ai volumi italiani del CIL. Latium vetus (CIL XIV; Eph. Epigr. VII e IX). 1. Latium vetus praeter Ostiam' },
			{ k: 'Suppl. It. – Roma', v: 'Supplementa Italica — Imagines: Supplementi fotografici ai volumi italiani del CIL. Roma. 1. Musei Capitolini. 2. Musei Vaticani 1 — Antiquarium Comunale del Celio' },
			{ k: 'TAM', v: 'Tituli Asiae minoris' },
			{ k: 'Ternes', v: 'Ternes, Les inscriptions antiques du Luxembourg, in: Hémecht 17, 1966, H. 3–4' },
			{ k: 'Thylander', v: 'Thylander, Inscriptions du port d’Ostie' },
			{ k: 'Vollmer', v: 'Vollmer, Inscriptiones Baivariae Romanae sive inscriptiones prov. Raetiae adiectis aliquot Noricis Italicisque' },
			{ k: 'Wagner', v: 'Wagner, Neue Inschriften aus Raetien, in: 37.–38. Bericht der Römisch-Germanischen Kommission 1956–1957, 215–264' },
			{ k: 'Weber, Suppl. CIL III', v: 'Weber, Supplementum epigraphicum zu CIL III für Salzburg, Steiermark, Oberösterreich und das norische Niederösterreich 1902–1964' },
			{ k: 'Zarker', v: 'Zarker, Studies in the Carmina Latina epigraphica' }
		]
	}
}
